import React from 'react';
import CaixaTexto from '../../components/CaixaTexto'

import './style.css'


function Historia(){
    return(
        <div>
           <CaixaTexto
           titulo='Sobre a história de Itan'
           texto='Embora essa seja uma história fictícia, o projeto buscou se basear em contextos históricos reais. Podemos imaginar quantas mães, irmãs, filhas e esposas foram arrancadas de seus entes queridos e levadas a força em um navio negreiro durante o período escravista. Esse jogo tem como objetivo mostrar as diversas faces da escravidão na América dentro da perspectiva dos escravizados.'
           span2='PISTA 1 - Ganhadeira Joana: "Naquela época era comum escravos venderem quitutes para seus senhores nas praças e ficarem com uma pequena porção dos ganhos para si. Joana era ganhadeira assim como Inaê e estava na praça quando ambos chegaram na Bahia. Ela lembra que Itan foi vendido para alguém que vivia na capital da província."='
           texto2='=> Os escravos de ganho eram muitos comuns em centros urbanos. Eles vendiam mercadorias variadas, especialmente verduras, horataliças, peixes, frutas e alimentos feitos por elas. O escravo que trabalhava com ganho, geralmente conseguia juntar dinheiro mais rápido para comprar sua alforria. Conforme a historiadora Cecília Soares, um grande número de escravos de ganhos eram composto por mulheres, uma vez que ganhadeiras africanas eram originárias de regiões na costa ocidental africana, onde o pequeno comércio era tarefa fundamentalmente feminina, assegurando papéis econômicos importantes para as mulheres. O serviço de ganho proporcionava livre trânsito pelas ruas, facilitando a comunicação entre escravos e libertos, o que ampliava suas relações sociais. Ao mesmo tempo, eram vistos como um perigo pela sociedade escravista e as autoridades que temiam revoltas e conflitos.'
           span3='PISTA 2 - Ignácio, o vendedor de peixe: "Ignácio vendia peixes quando viu Itan correndo pelo mercado com seu senhor. Ele dizia que iria viajar para um lugar conhecido por seus charutos.  O tráfico de escravos para a América foi proibido desde 1831, embora as décadas de 1840 e 1850 tiveram um grande número de africanos levados para servirem de escravos em países como Brasil e Cuba."='
           texto3='=> No Brasil, no começo dos anos 1830, iniciou o processo de proibição do tráfico, que se estendeu até a década de 1850, quando finalmente o tráfico foi finalizado. A Dinamarca já havia abolido o comércio de escravos em 1792, enquanto os Estados Unidos e a Grã-Bretanha decretaram a proibição a partir de 1808. Apesar da proibição do comércio de escravos, Sidney Chalhoub afirma que 42% das importações de africanos para o Brasil desde o século XVI, aconteceram durante o século XIX.  Pierre Verger demonstrou as diversas manobras que traficantes de escravos usaram para burlar a fiscalização nos portos durante o período ilegal, que incluíram desembarques clandestinos em outras regiões do litoral baiano, mudança de bandeira na embarcação e arqueação do navio, carregando capacidade maior ao que realmente tinham. Em 1850, as fazendas de café estavam repletas de trabalhadores reduzidos à condição de escravos ilegalmente. Outros países continuaram recebendo escravizados que saíam da costa africana. O historiador Robin Law afirma que pelo menos até 1857 ainda havia notícias de tráfico em Uidá, até mesmo de escravos vindos de Lagos, ambas na costa ocidental. O comércio negreiro continuou sendo a atividade mais lucrativa na costa africana, mesmo depois da proibição do tráfico, pelo menos até a década de 1860.'
           span4='Dica 3 - Esperança, africana liberta: "Esperança viu um menino e seu senhor caminhando pelos portos cubanos com as mesmas descrições que Inaê fez. Parece que estavam a bordo de um navio negreiro. O senhor de Itan levava escravizados para uma região de pampas e criação de gado, lá no Brasil. Parece que Itan era seu ajudante pessoal." ='
           texto4='=> O comércio de escravos percorria todo o Oceano Atlântico, englobando países como Cuba e Brasil. Era comum o comércio entre países escravistas. Sobre a escravidão em Cuba, os historiadores Rebecca Scott e Jean Hébrard demonstram as relações escravistas no tráfico, cotidiano e demais comércios não só em Cuba, como nos Estados Unidos. Eles analisam a trajetória de uma família inteira, iniciando com a chegada da africana Rosalie na América, até seus descendentes envolvidos no comércio de charuto. Eles demonstram como os libertos precisavam provar sua liberdade constantemente e os medos da reescravização. Outro trabalho importante se refere à resistência escrava em Cuba, realizado pela Historiadora Iacy Maia. / Sobre o tráfico interprovincial, podemos destacar o grande aumento de vendas entre províncias brasileiras após a proibição total do tráfico, em 1850. O arquivo histórico da  Bahia está repleto de pedidos de passaportes acompanhados por carta de compra e venda de escravos para o sul do país.'
           span5='DICA 4 - a africana Maria de Jesus: "Maria de Jesus foi levada junto com Itan para o Rio Grande do Sul e vendida para trabalhar como ganhadeira nas ruas da cidade. Ela conta que Itan realmente trabalha diretamente com seu senhor, como ajudante na compra e venda de escravizados. Parece que eles partiram no último navio em direção à terra natal de Itan."='
           texto5='=>'
           />
        </div>
    )
}


export default Historia